---
- name: My task
  hosts: all
  remote_user: flo
  tasks:
     - name: Leaving a mark
       command: "touch /tmp/ansible_was_here"
     - name: Providing feedback
       command: echo "The Playbook works"
       register: feedback
     - debug: msg="{{feedback.stdout}}"