---
- name: Change password
  hosts: all
  remote_user: flo
  become: true
  vars:
    ansible_become_pass: "{{ root_pass }}"
  tasks:
    - user:
        name: flo
        update_password: always
        password: "{{ new_root_pass | password_hash('sha512') }}"