---
- hosts: netcup
  remote_user: "{{ remote_user }}"
  become: true
  vars:
    ansible_become_pass: "{{ root_pass }}"
  tasks:
    - name: Run Roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ roles }}"
