---
- name: Setup Backup
  hosts: netcup
  remote_user: "{{ user }}"
  become: true
  vars:
    ansible_become_pass: "{{ root_pass }}"
  roles:
    - backup

- name: Setup Storage
  hosts: khadas
  remote_user: "{{ backup_user }}"
  become: true
  vars:
    ansible_become_pass: "{{ root_pass }}"
  tasks:
  roles:
    - backupRetrival
