- name: Install Nginx
  apt:
    pkg:
      - nginx

- name: Deploy Custom configs
  template:
    mode: 0744
    src: site.cfg
    dest: /etc/nginx/sites-available/site.cfg
  notify: Restart Nginx

- name: Create Symlink
  file:
    src: /etc/nginx/sites-available/site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx
