---
- name: Create Vaultwarden folder
  ansible.builtin.file:
    path: /srv/vaultwarden/
    owner: flo
    group: flo
    state: directory
    mode: '0775'

- name: Deploy Vaultwarden
  community.docker.docker_container:
    image: vaultwarden/server
    name: vaultwarden
    state: started
    restart_policy: unless-stopped
    purge_networks: true
    network_mode: default
    networks:
      - name: "traefik"
    volumes:
      - /srv/vaultwarden:/data
    env:
      WEBSOCKET_ENABLED: "true"  # Required to use websockets
      SIGNUPS_ALLOWED: "false"   # set to false to disable signups
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
      LOG_FILE: "/data/vaultwarden.log"
    labels:
      traefik.enable: "true"
      # Vaultwarden UI
      traefik.http.routers.vaultwarden-ui.rule: "Host(`vaultwarden.{{ base_url | string }}`)"
      traefik.http.routers.vaultwarden-ui.entrypoints: "web-secure"
      traefik.http.routers.vaultwarden-ui.tls: "true"
      traefik.http.routers.vaultwarden-ui.tls.certresolver: "cert-reitz"
      traefik.http.routers.vaultwarden-ui.service: "vaultwarden-ui-lb"
      # Vaultwarden UI HTTPS-Upgrade
      traefik.http.routers.vaultwarden-ui-unsecure.rule: "Host(`vaultwarden.{{ base_url | string }}`)"
      traefik.http.routers.vaultwarden-ui-unsecure.entrypoints: "web"
      traefik.http.routers.vaultwarden-ui-unsecure.middlewares: "redirect-https@file"
      traefik.http.routers.vaultwarden-ui-unsecure.service: "vaultwarden-ui-lb"
      # Vaultwarden Websocket
      traefik.http.routers.vaultwarden-websocket.rule: "Host(`vaultwarden.{{ base_url | string }}`) && Path(`/notifications/hub`)"
      traefik.http.routers.vaultwarden-websocket.entrypoints: "web-secure"
      traefik.http.routers.vaultwarden-websocket.tls: "true"
      traefik.http.routers.vaultwarden-websocket.tls.certresolver: "cert-reitz"
      traefik.http.routers.vaultwarden-websocket.service: "vaultwarden-websocket-lb"
      # Vaultwarden Websocket HTTPS-Upgrade
      traefik.http.routers.vaultwarden-websocket-unsecure.rule: "Host(`vaultwarden.{{ base_url | string }}`) && Path(`/notifications/hub`)"
      traefik.http.routers.vaultwarden-websocket-unsecure.entrypoints: "web"
      traefik.http.routers.vaultwarden-websocket-unsecure.middlewares: "redirect-https@file"
      traefik.http.routers.vaultwarden-websocket-unsecure.service: "vaultwarden-websocket-lb"
      # load-Balancer to route to another port
      traefik.http.services.vaultwarden-websocket-lb.loadbalancer.server.port: "3012"
      traefik.http.services.vaultwarden-ui-lb.loadbalancer.server.port: "80"
